# Generated by Django 5.1.4 on 2024-12-17 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField(default=0, verbose_name='Опыт')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.table1')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имя',
            },
        ),
        migrations.CreateModel(
            name='Table4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0, verbose_name='Зарплата')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.table1')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Зарплата',
            },
        ),
    ]
